### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by Emma-Hyejin** [Emma-Hyejin/todo-v2#1]
### 구현 예정 기능
Todo 생성 기능 

### 해당 기능을 구현하기 위해 할 일 
1. [ ] Todo 입력 창 구현
2. [ ] Todo 입력 받은 내용 출력 단 구현 
3. [ ] localStorage  | json-server 생성 및 이용

### 예상 작업 시간 ( Total : 4h )
1. 2h
2. 1h
3. 1h
